### PR TITLE
Fix formating of the logo

### PR DESCRIPTION
**Pull request by realvictorprm**
Looks a bit weird, just a suggestion ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by msc-** [comment]
What do you think looks a bit weird? I think the logo is still too large w.r.t. the title text size. I don't know if it is possible to specify an image size in Markdown. If possible, please reduce the size.

**Comment by realvictorprm** [comment]
Text and Image are currently on the same line. However I agree it's a bit too large, let me see what I can do :)

**Comment by msc-** [comment]
> Text and Image are currently on the same line.

Oh! When I viewed README.md in your fork the text was on a different line so I thought you'd fixed that particular problem.

**Comment by realvictorprm** [comment]
@msc- Done, better so?

**Comment by realvictorprm** [comment]
If you need a different size just tell me, I'll amend the commit :smile:

**Comment by msc-** [comment]
A little bit smaller I think. Maybe 300.

**Comment by realvictorprm** [comment]
@msc fixed :)

**Comment by msc-** [comment]
Thanks for this.  I have resolved the issue with Appveyor so merging now.

**Comment by realvictorprm** [comment]
Nice! Thanks @msc 🥇

**Pull request merged**
